filebeat.config:
  modules:
    path: /host/opt/netwatch/etc/elastic/filebeat/modules.d/*.yml
    reload.enabled: false

filebeat.modules:
- module: suricata
  eve:
    enabled: true
    var.paths: ["/host/opt/netwatch/suricata/log/eve.json"]


#filebeat.autodiscover:
#  providers:
#    - type: docker
#      hints.enabled: true

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["https://your.elasticsearch.instance"]
  username: "create-a-user-in-kibana-with appropriate-permissions-then-add-that-info-here"
  password: "see username"
